const features = [
  {
    key: 'climate-patterns',
    title: 'Climate Patterns',
    icon: '🌍',
    description: 'Analyze global climate patterns including ENSO, NAO, and jet stream dynamics',
    apiPath: '/climate-patterns',
    aiEndpoint: '/ai/analyze-pattern',
    aiDataKey: 'patternData',
    columns: ['name', 'pattern_type', 'region', 'severity'],
    formFields: [
      { name: 'name', label: 'Pattern Name', type: 'text', required: true },
      { name: 'pattern_type', label: 'Pattern Type', type: 'text' },
      { name: 'region', label: 'Region', type: 'text' },
      { name: 'severity', label: 'Severity', type: 'select', options: ['Low', 'Moderate', 'High', 'Critical'] },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'name',
    badgeField: 'severity',
  },
  {
    key: 'weather-forecasts',
    title: 'Weather Forecasts',
    icon: '⛅',
    description: 'Real-time weather forecasts for cities with AI-powered analysis',
    apiPath: '/weather-forecasts',
    aiEndpoint: '/ai/forecast-analysis',
    aiDataKey: 'forecastData',
    columns: ['location', 'conditions', 'temperature_high', 'precipitation_chance'],
    formFields: [
      { name: 'location', label: 'Location', type: 'text', required: true },
      { name: 'forecast_date', label: 'Forecast Date', type: 'date' },
      { name: 'temperature_high', label: 'High Temp (°C)', type: 'number' },
      { name: 'temperature_low', label: 'Low Temp (°C)', type: 'number' },
      { name: 'precipitation_chance', label: 'Precipitation %', type: 'number' },
      { name: 'wind_speed', label: 'Wind Speed (mph)', type: 'number' },
      { name: 'humidity', label: 'Humidity %', type: 'number' },
      { name: 'conditions', label: 'Conditions', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'location',
    badgeField: 'conditions',
  },
  {
    key: 'temperature-predictions',
    title: 'Temperature Predictions',
    icon: '🌡️',
    description: 'AI-powered temperature predictions with model accuracy tracking',
    apiPath: '/temperature-predictions',
    aiEndpoint: '/ai/temperature-analysis',
    aiDataKey: 'tempData',
    columns: ['region', 'predicted_temp', 'actual_temp', 'confidence'],
    formFields: [
      { name: 'region', label: 'Region', type: 'text', required: true },
      { name: 'prediction_date', label: 'Prediction Date', type: 'date' },
      { name: 'predicted_temp', label: 'Predicted Temp (°C)', type: 'number' },
      { name: 'actual_temp', label: 'Actual Temp (°C)', type: 'number' },
      { name: 'confidence', label: 'Confidence %', type: 'number' },
      { name: 'model_used', label: 'Model Used', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'region',
  },
  {
    key: 'precipitation-analysis',
    title: 'Precipitation Analysis',
    icon: '🌧️',
    description: 'Rainfall patterns, drought indices, and water resource analysis',
    apiPath: '/precipitation-analysis',
    aiEndpoint: '/ai/precipitation-analysis',
    aiDataKey: 'precipData',
    columns: ['region', 'analysis_period', 'total_rainfall', 'drought_index'],
    formFields: [
      { name: 'region', label: 'Region', type: 'text', required: true },
      { name: 'analysis_period', label: 'Analysis Period', type: 'text' },
      { name: 'total_rainfall', label: 'Total Rainfall (mm)', type: 'number' },
      { name: 'avg_rainfall', label: 'Avg Rainfall (mm)', type: 'number' },
      { name: 'max_rainfall', label: 'Max Rainfall (mm)', type: 'number' },
      { name: 'drought_index', label: 'Drought Index', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'region',
  },
  {
    key: 'drought-assessments',
    title: 'Drought Assessments',
    icon: '🏜️',
    description: 'Comprehensive drought risk analysis with soil and vegetation monitoring',
    apiPath: '/drought-assessments',
    aiEndpoint: '/ai/drought-analysis',
    aiDataKey: 'droughtData',
    columns: ['region', 'risk_level', 'drought_index', 'soil_moisture'],
    formFields: [
      { name: 'region', label: 'Region', type: 'text', required: true },
      { name: 'risk_level', label: 'Risk Level', type: 'select', options: ['Low', 'Moderate', 'High', 'Critical'] },
      { name: 'drought_index', label: 'Drought Index', type: 'number' },
      { name: 'soil_moisture', label: 'Soil Moisture %', type: 'number' },
      { name: 'vegetation_index', label: 'Vegetation Index', type: 'number' },
      { name: 'water_reserves', label: 'Water Reserves %', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'region',
    badgeField: 'risk_level',
  },
  {
    key: 'flood-predictions',
    title: 'Flood Predictions',
    icon: '🌊',
    description: 'River level monitoring and flood risk forecasting for vulnerable regions',
    apiPath: '/flood-predictions',
    aiEndpoint: '/ai/flood-analysis',
    aiDataKey: 'floodData',
    columns: ['region', 'risk_level', 'river_level', 'population_affected'],
    formFields: [
      { name: 'region', label: 'Region', type: 'text', required: true },
      { name: 'risk_level', label: 'Risk Level', type: 'select', options: ['Low', 'Moderate', 'High', 'Critical'] },
      { name: 'river_level', label: 'River Level (m)', type: 'number' },
      { name: 'rainfall_forecast', label: 'Rainfall Forecast (mm)', type: 'number' },
      { name: 'soil_saturation', label: 'Soil Saturation %', type: 'number' },
      { name: 'population_affected', label: 'Population Affected', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'region',
    badgeField: 'risk_level',
  },
  {
    key: 'storm-tracking',
    title: 'Storm Tracking',
    icon: '🌀',
    description: 'Track hurricanes, typhoons, cyclones and severe weather events globally',
    apiPath: '/storm-tracking',
    aiEndpoint: '/ai/storm-analysis',
    aiDataKey: 'stormData',
    columns: ['storm_name', 'storm_type', 'category', 'wind_speed'],
    formFields: [
      { name: 'storm_name', label: 'Storm Name', type: 'text', required: true },
      { name: 'storm_type', label: 'Storm Type', type: 'text' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'current_location', label: 'Current Location', type: 'text' },
      { name: 'wind_speed', label: 'Wind Speed (km/h)', type: 'number' },
      { name: 'pressure', label: 'Pressure (mb)', type: 'number' },
      { name: 'direction', label: 'Direction', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'storm_name',
    badgeField: 'category',
  },
  {
    key: 'sea-level-projections',
    title: 'Sea Level Projections',
    icon: '🌅',
    description: 'Coastal vulnerability assessment and sea level rise projections',
    apiPath: '/sea-level-projections',
    aiEndpoint: '/ai/sea-level-analysis',
    aiDataKey: 'seaLevelData',
    columns: ['coastal_region', 'projected_rise', 'projection_year', 'confidence'],
    formFields: [
      { name: 'coastal_region', label: 'Coastal Region', type: 'text', required: true },
      { name: 'current_level', label: 'Current Level (m)', type: 'number' },
      { name: 'projected_rise', label: 'Projected Rise (m)', type: 'number' },
      { name: 'projection_year', label: 'Projection Year', type: 'number' },
      { name: 'confidence', label: 'Confidence %', type: 'number' },
      { name: 'impact_assessment', label: 'Impact Assessment', type: 'textarea' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'coastal_region',
  },
  {
    key: 'air-quality',
    title: 'Air Quality Index',
    icon: '💨',
    description: 'Real-time air quality monitoring with health impact assessments',
    apiPath: '/air-quality',
    aiEndpoint: '/ai/air-quality-analysis',
    aiDataKey: 'aqData',
    columns: ['location', 'aqi_value', 'category', 'pm25'],
    formFields: [
      { name: 'location', label: 'Location', type: 'text', required: true },
      { name: 'aqi_value', label: 'AQI Value', type: 'number' },
      { name: 'pm25', label: 'PM2.5', type: 'number' },
      { name: 'pm10', label: 'PM10', type: 'number' },
      { name: 'ozone', label: 'Ozone', type: 'number' },
      { name: 'co_level', label: 'CO Level', type: 'number' },
      { name: 'category', label: 'Category', type: 'select', options: ['Good', 'Moderate', 'Unhealthy for Sensitive', 'Unhealthy', 'Very Unhealthy', 'Hazardous'] },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'location',
    badgeField: 'category',
  },
  {
    key: 'carbon-emissions',
    title: 'Carbon Emissions',
    icon: '🏭',
    description: 'Track and analyze carbon emissions by sector with reduction targets',
    apiPath: '/carbon-emissions',
    aiEndpoint: '/ai/carbon-analysis',
    aiDataKey: 'carbonData',
    columns: ['source', 'emission_type', 'sector', 'amount_tons'],
    formFields: [
      { name: 'source', label: 'Source', type: 'text', required: true },
      { name: 'emission_type', label: 'Emission Type', type: 'select', options: ['CO2', 'CH4', 'N2O', 'HFC'] },
      { name: 'amount_tons', label: 'Amount (tons)', type: 'number' },
      { name: 'measurement_date', label: 'Measurement Date', type: 'date' },
      { name: 'sector', label: 'Sector', type: 'text' },
      { name: 'reduction_target', label: 'Reduction Target %', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'source',
  },
  {
    key: 'crop-yield-predictions',
    title: 'Crop Yield Predictions',
    icon: '🌾',
    description: 'Agricultural yield forecasting based on climate conditions',
    apiPath: '/crop-yield-predictions',
    aiEndpoint: '/ai/crop-yield-analysis',
    aiDataKey: 'cropData',
    columns: ['crop_name', 'region', 'predicted_yield', 'climate_impact'],
    formFields: [
      { name: 'crop_name', label: 'Crop Name', type: 'text', required: true },
      { name: 'region', label: 'Region', type: 'text' },
      { name: 'predicted_yield', label: 'Predicted Yield', type: 'number' },
      { name: 'unit', label: 'Unit', type: 'text' },
      { name: 'season', label: 'Season', type: 'text' },
      { name: 'climate_impact', label: 'Climate Impact', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'crop_name',
    badgeField: 'climate_impact',
  },
  {
    key: 'insurance-risk',
    title: 'Insurance Risk Assessment',
    icon: '🛡️',
    description: 'Climate-related insurance risk scoring and premium analysis',
    apiPath: '/insurance-risk',
    aiEndpoint: '/ai/insurance-risk-analysis',
    aiDataKey: 'insuranceData',
    columns: ['property_type', 'location', 'risk_score', 'climate_risk_factor'],
    formFields: [
      { name: 'property_type', label: 'Property Type', type: 'select', options: ['Residential', 'Commercial', 'Industrial', 'Agricultural'], required: true },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'risk_score', label: 'Risk Score (1-10)', type: 'number' },
      { name: 'climate_risk_factor', label: 'Climate Risk Factor', type: 'text' },
      { name: 'premium_adjustment', label: 'Premium Adjustment %', type: 'number' },
      { name: 'coverage_recommendation', label: 'Coverage Recommendation', type: 'textarea' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'location',
  },
  {
    key: 'real-estate-climate-risk',
    title: 'Real Estate Climate Risk',
    icon: '🏠',
    description: 'Property-level climate risk assessment for real estate investments',
    apiPath: '/real-estate-climate-risk',
    aiEndpoint: '/ai/real-estate-analysis',
    aiDataKey: 'realEstateData',
    columns: ['property_address', 'city', 'risk_score', 'flood_risk'],
    formFields: [
      { name: 'property_address', label: 'Property Address', type: 'text', required: true },
      { name: 'city', label: 'City', type: 'text' },
      { name: 'risk_score', label: 'Risk Score (1-10)', type: 'number' },
      { name: 'flood_risk', label: 'Flood Risk', type: 'select', options: ['Low', 'Moderate', 'High', 'Extreme'] },
      { name: 'fire_risk', label: 'Fire Risk', type: 'select', options: ['Low', 'Moderate', 'High', 'Extreme'] },
      { name: 'heat_risk', label: 'Heat Risk', type: 'select', options: ['Low', 'Moderate', 'High', 'Extreme'] },
      { name: 'projected_impact', label: 'Projected Impact', type: 'textarea' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'property_address',
    badgeField: 'flood_risk',
  },
  {
    key: 'historical-climate-data',
    title: 'Historical Climate Data',
    icon: '📊',
    description: 'Historical climate records and trend analysis spanning centuries',
    apiPath: '/historical-climate-data',
    aiEndpoint: '/ai/historical-analysis',
    aiDataKey: 'historicalData',
    columns: ['region', 'time_period', 'avg_temperature', 'trend'],
    formFields: [
      { name: 'region', label: 'Region', type: 'text', required: true },
      { name: 'time_period', label: 'Time Period', type: 'text' },
      { name: 'avg_temperature', label: 'Avg Temperature (°C)', type: 'number' },
      { name: 'avg_precipitation', label: 'Avg Precipitation (mm)', type: 'number' },
      { name: 'notable_events', label: 'Notable Events', type: 'textarea' },
      { name: 'trend', label: 'Trend', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'region',
    badgeField: 'trend',
  },
  {
    key: 'climate-alerts',
    title: 'Climate Alerts',
    icon: '🚨',
    description: 'Active climate alerts, warnings, and emergency notifications',
    apiPath: '/climate-alerts',
    aiEndpoint: '/ai/alert-analysis',
    aiDataKey: 'alertData',
    columns: ['alert_type', 'severity', 'region', 'active'],
    formFields: [
      { name: 'alert_type', label: 'Alert Type', type: 'text', required: true },
      { name: 'severity', label: 'Severity', type: 'select', options: ['Low', 'Moderate', 'High', 'Critical', 'Extreme'] },
      { name: 'region', label: 'Region', type: 'text' },
      { name: 'message', label: 'Message', type: 'textarea' },
      { name: 'active', label: 'Active', type: 'select', options: ['true', 'false'] },
      { name: 'expires_at', label: 'Expires At', type: 'date' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    primaryField: 'alert_type',
    badgeField: 'severity',
  },
];

export default features;
